# str="My is name is shrawan is kumar"
# print(len(str))
# # print(str[0::4])
# print(str.isalnum())
# print(str.isalpha())
# print(str.endswith("kumar"))
# print(str.count("a"))
# print(str.lower())
# print(str.capitalize())
# print(str.upper())
# print(str.replace("is","are"))